application:
  group: bycza-zagroda
  version: 0.1

#Datasource
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost/trackexpensesapp?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: db/dbchangelog-test.yaml
  #Jpa/Hibernate:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  port: 8090