#Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trackexpensesapptest?useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_empty

  liquibase:
    change-log: db/dbchangelog-test.yaml

server:
  port: 8090

jwt:
  secret: blabla
  exp: 604800000 # one week
  refresh-exp: 31536000000 # one year
