#Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trackexpensesapptest?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_empty

  liquibase:
    change-log: db/dbchangelog-test.yaml
    drop-first: true

server:
  port: 8090
