package pl.byczazagroda.trackexpensesappbackend.mapper;

import pl.byczazagroda.trackexpensesappbackend.dto.FinancialTransactionCategoryDTO;
import pl.byczazagroda.trackexpensesappbackend.model.FinancialTransactionCategory;

public interface FinancialTransactionCategoryModelMapper {
    FinancialTransactionCategoryDTO mapFinancialTransactionCategoryEntityToFinancialTransactionCategoryDTO(FinancialTransactionCategory category);
}
